accounts/urls.py
from django.urls import path

import accounts.views

urlpatterns = [
    #path('',accounts.views.login,name='login'),
    #    path('<int:blogid>/',accounts.views.detail,name='details'),
    path('signup/',accounts.views.signup,name='signup'),
    path('login/',accounts.views.login,name='login'),
    path('logout/',accounts.views.logout,name='logout'),

]

holdings/urls.py
from django.urls import path
from django.conf.urls import url
import holdings.views
from .views import ProductAutocompleteView
from .views import ViewDummyUserCreate4,ViewDummyUserCreate5,ViewUpdatePost


urlpatterns = [
    #path('',accounts.views.login,name='login'),
    #    path('<int:blogid>/',accounts.views.detail,name='details'),
    #path('addmutual2/',holdings.views.addmutual2,name='addmutual2'),
    path('portfolio/',holdings.views.portfolio,name='portfolio'),
    path('portfolio/delmutual/',holdings.views.delmutual,name='delmutual'),
  #  path('portfolio/<int:pk>/update/',ViewUpdatePost.as_view(), name='editmutual'),
 #   path('editmutual/<int:pk>/',
    url(r'^addmutual/product-autocomplete/$', ProductAutocompleteView.as_view(), name='product-autocomplete'),
    url(r'^addmutual/$', ViewDummyUserCreate4.as_view(), name='addmutual'),
    url(r'^addmutualsip/$', ViewDummyUserCreate5.as_view(), name='addmutualsip'),
    url(r'^update/(?P<pk>\d+)$', ViewUpdatePost.as_view(), name="editmutual"),
    #url(r'^editmutual/<int:pk>/update/$', ViewUpdatePost.as_view(), name='editmutual'),

    
      
]

projecthunt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import products.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',products.views.home,name='homepage'),
    path('mutualfunds/',products.views.mutualfunds,name='mutualfunds'),
    path('accounts/',include('accounts.urls')),
    path('products/',include('products.urls')),
    path('holdings/',include('holdings.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

holdings/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

# Create your models here.

class Holdingmutual(models.Model):
    no_shares=models.IntegerField(default=None)#amfi code for product
    #rating=models.IntegerField(default=1)#rating of stock
    #image=models.ImageField(upload_to='images/')
    #icon=models.ImageField(upload_to='images/',null=True)
    start_date=models.DateField(default=None)
    sip_date=models.DateField(default=None,null=True)
    notes=models.TextField(default=None,blank=True)#Notes
    investment_type=models.CharField(max_length=10,default='unknown',blank=True)#Investment type buy or sip
    productid=models.ForeignKey('products.Product',on_delete=models.CASCADE)
    userid=models.ForeignKey(User,on_delete=models.CASCADE)

 
    def summary(self):
        return self.body[:100]

    def pub_date_pretty(self):
        return self.pub_date.strftime("%d %a %Y")
    
    def __str__(self):
        return '%s' % self.productid

    def get_absolute_url(self):
        return reverse('portfolio')

class Holdingmutualsip(models.Model):
    
    #rating=models.IntegerField(default=1)#rating of stock
    #image=models.ImageField(upload_to='images/')
    #icon=models.ImageField(upload_to='images/',null=True)
    def return_date_time():
        now = timezone.now()
        return now + timedelta(days=1000)
    
    date=models.DateField(default=None)
    end_date=models.DateField(default=return_date_time)    
    userid=models.ForeignKey(User,on_delete=models.CASCADE)
    invest_amount=models.IntegerField(default=None)#amfi code for product 
    productid=models.ForeignKey('products.Product',on_delete=models.CASCADE)  
    
      
    def summary(self):
        return self.body[:100]

    def pub_date_pretty(self):
        return self.pub_date.strftime("%d %a %Y")
    
    def __str__(self):
        return '%s' % self.productid

    def get_absolute_url(self):
        return reverse('portfolio')

holdings/forms.py
from django.forms import ModelForm
from django import forms
from .models import Holdingmutual,Holdingmutualsip
from products.models import Product
from dal import autocomplete



class MutualForm(forms.ModelForm):    
    #productid = forms.ModelChoiceField(queryset=Product.objects.all())
    # productid = forms.ModelChoiceField(queryset=Product.objects.all(),
    # widget=autocomplete.ModelSelect2(url='product-autocomplete')
    # )
    notes=forms.CharField(
        required=False,
        widget=forms.Textarea(
                attrs={
                    "class":"my-text-class",
                    "rows":5,
                    "cols":120,
                    "id": "my-id-text"
                }
            )
        )
    class Meta:
         model=Holdingmutual
         #fields='__all__'
         exclude=['userid']
         widgets = {'start_date': forms.DateInput(attrs={'class': 'datepicker' }),
         'sip_date': forms.DateInput(attrs={'class': 'datepicker' }),
         'productid':autocomplete.ModelSelect2(url='product-autocomplete',
         attrs={
            'theme': 'bootstrap',
            'data-minimum-input-length': 3,
        })
         }
         
#   def __init__(self, *args, **kwargs):
#      super(MutualForm, self).__init__(*args, **kwargs)
#      self.fields['no_shares'].label = "No of Shares"
#      self.fields['productid'].label = "Mutual Fund"


class MutualForm2(forms.ModelForm):    
    #productid = forms.ModelChoiceField(queryset=Product.objects.all())
    # productid = forms.ModelChoiceField(queryset=Product.objects.all(),
    # widget=autocomplete.ModelSelect2(url='product-autocomplete')
    # )
    notes=forms.CharField(
        required=False,
        widget=forms.Textarea(
                attrs={
                    "class":"my-text-class",
                    "rows":5,
                    "cols":120,
                    "id": "my-id-text"
                }
            )
        )
    class Meta:
         model=Holdingmutualsip
         #fields='__all__'
         exclude=['userid','investment_type']
         widgets = {'date': forms.DateInput(attrs={'class': 'datepicker' }),
         'productid':autocomplete.ModelSelect2(url='product-autocomplete',
         attrs={
            'theme': 'bootstrap',
            'data-minimum-input-length': 3,
        })
         }
         
#   def __init__(self, *args, **kwargs):
#      super(MutualForm, self).__init__(*args, **kwargs)
#      self.fields['no_shares'].label = "No of Shares"
#      self.fields['productid'].label = "Mutual Fund" 

holdings/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import  Holdingmutual,Holdingmutualsip
from products.models import Product
from .forms import MutualForm,MutualForm2
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.response import Response 
from dal import autocomplete
#from django.views.generic.edit import CreateView
from django.views.generic import CreateView, UpdateView
from django.http import HttpResponseRedirect
from django.urls import reverse
from pprint import pprint
import requests

#from django.core.urlresolvers import reverse_lazy


# Create your views here.
def addmutual5(request):
    mutualfunds= Product.objects
    return render(request,'holdings/addmutual5.html',{'mutualfunds':mutualfunds})

def portfolio(request):
    holdings= Holdingmutual.objects.filter(userid_id=request.user.id)
    #pprint(holdings)
    products= Product.objects
    portfolioList=[]
    sumtotal=0
    for holding in holdings:
        productcode=get_object_or_404(Product,pk=holding.productid_id)
        url = 'https://www.quandl.com/api/v3/datasets/AMFI/'+str(productcode.stockid)+'.json?api_key=a6QtRRy_axhp9mTMRvyC'
        #print(url)
        response=requests.get(url)
        stockdetail=response.json()
        navst=stockdetail['dataset']['data'][0][1]
        navstotal=(navst*holding.no_shares)
        #print(navst)
        # Creation of a list with all values required for portfolio
        portfList=[
                   holding.id,
                   productcode.title,
                   holding.no_shares,
                   holding.start_date,
                   holding.sip_date,
                   holding.notes,
                   navst,
                   navstotal,
                   holding.productid_id,
                   productcode.stockid
                   ]
        portfolioList.append(portfList)
        sumtotal=sumtotal+navstotal
        #pprint(portfolioList)
    return render(request,'holdings/portfolio.html',{'portfolioList':portfolioList,'productList':products,'sumtotal':sumtotal})
@login_required
def addmutual(request):
    if request.method == "POST":
        form = MutualForm(data=request.POST)
        if form.is_valid():
            print("form is valide")
            mutual_form = form.save(commit=False)
            mutual_form.userid_id=request.user.id
            mutual_form.save()
            return redirect('portfolio')
        else:
            print("form is not valide")
            print(request.user)

    else:
        form = MutualForm()
    return render(request, 'holdings/addmutual.html',{'form':form})
@login_required    
def delmutual(request):
    if request.method == "POST":
        if request.method == 'POST':
            holdid=request.POST['mfund2']
            Holdingmutual.objects.filter(id=holdid).delete()
            print("record deleted"+request.POST['mfund2'])
            return redirect('portfolio')
        return redirect('portfolio')

#example class view- code not used

class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        
        labels = ["Users", "Blue", "Yellow", "Green", "Purple", "Orange"]
        default_items = [23, 2, 3, 12, 2]
        data = {
                "labels": labels,
                "default": default_items,
        }
        return Response(data)

##autocomplete view
class ProductAutocompleteView(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Product.objects.none()

        qs = Product.objects.all()

        if self.q:
            qs = qs.filter(title__icontains=self.q)
        
        return qs

class ViewDummyUserCreate4(CreateView):
    # make a form based on this model
    model = Holdingmutual
    # if we only want to edit these two fields
    # fields = ('first_name', 'last_name')
    form_class = MutualForm
    #fields = '__all__'
 
    # render this html file, pass a form object to that file
    template_name = 'holdings/addmutual.html'
 
    def form_valid(self, form):
        print("form is valide")
        mutual_form2 = form.save(commit=False)
        mutual_form2.submitted_by = self.request.user
        mutual_form2.userid_id=self.request.user.id
        mutual_form2.investment_type="BUY"
        mutual_form2.save()       
        return HttpResponseRedirect(self.get_success_url())
 
    def get_success_url(self):
        return reverse('portfolio')
class ViewDummyUserCreate5(CreateView):
    # make a form based on this model
    model = Holdingmutualsip
    print("form is enterred")
    # if we only want to edit these two fields
    # fields = ('first_name', 'last_name')
    form_class = MutualForm2
    #fields = '__all__'
 
    # render this html file, pass a form object to that file
    template_name = 'holdings/addmutualsip.html'
 
    def form_valid(self, form):
        print("form is valide")
        mutual_form2 = form.save(commit=False)
        mutual_form2.submitted_by = self.request.user
        mutual_form2.userid_id=self.request.user.id
        mutual_form2.save()       
        return HttpResponseRedirect(self.get_success_url())
 
    def get_success_url(self):
        return reverse('portfolio')

#Have to implement user based checking
class ViewUpdatePost(UpdateView): 
    model = Holdingmutual
    #form_class = MutualForm
    template_name = 'holdings/editmutual.html'
    fields = ['no_shares','start_date','sip_date','notes']
    #success_url='holdings/portfolios'
    queryset=Holdingmutual.objects.all()
    
 
    def get_object(self):
        #holdid=self.request.POST['mfund2']
        #print("holdid got  ** -"+holdid)
        print("get_object_worked"+self.kwargs['pk'])
        id = self.kwargs['pk']
        return self.model.objects.get(pk=self.kwargs['pk'])
        #return get_object_or_404(Holdingmutual,id=self.kwargs['pk'])
   # def get_initial(self):
   #     return { 'no_shares': 'foo', 'start_date': 'bar','sip_date': 'bar','notes': 'bar' }
 
    def form_valid(self, form):
        print("form is valide")
        mutual_form2 = form.save(commit=False)
        mutual_form2.save()       
        return HttpResponseRedirect(self.get_success_url())
 
    def get_success_url(self):
        return reverse('portfolio')

holdings/templates/holdings/addmutual.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% if error %}
{{ error }}
<br />
<br />
{% endif %}
<div class="container-fluid"></div>
    <div class="row d-flex h-75 justify-content-center align-items-center mb-2">
            <div class="col-xs-12 center-block text-center">
            </div>
    </div>
    <div class="row">
        <div class="d-sm-flex align-items-center justify-content-between mb-2">
        </div>
  </div>
    <!-- Content Row start --> 
    <div class="row d-flex h-75 justify-content-center align-items-center mb-2">
    
        <div class="col-2 d-flex flex-column"></div>
    <!-- Content column start --> 

        <div class="col-8 d-flex flex-column">
    <!-- card start -->
        <div class="card shadow px-4">
          <div style="text-align:center;border:1px"><h5>Add Mutual Fund</h5></div>     
            <form action='.' method='POST' id="otherFieldDiv">{% csrf_token %}
                <div class="form-group">

                    {{ form.productid|as_crispy_field }}

                </div>
                <div class="form-group w-50">

                    {{ form.no_shares|as_crispy_field }}

                </div>
                <div class="form-group w-50">

                    {{ form.start_date|as_crispy_field }}

                </div>                             

                <div class="form-group w-50" >

                    {{ form.sip_date|as_crispy_field }}

                </div>
                <div class="form-group">

                    {{ form.notes|as_crispy_field }}

                </div>
                <div class="form-group">
                    <div class="text-right">
                        <button class="btn btn-info pull-right" type="submit" >Add Product</button>
                    </div>
                </div>
            </form>

            </div>
    <!-- card end -->
        </div>
    <!-- Content column end -->

     <div class="col-2 d-flex flex-column"></div>
    </div>
    <!-- Content Row End --> 
</div>
<script>
    $(function () {
        $("#id_sip_date").datepicker();
    });
</script>
<script>
    $(function () {
        $("#id_start_date").datepicker();
    });
</script>


{{ form.media }}
{% endblock %}

holdings/templates/holdings/addmutual2.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% if error %}
{{ error }}
<br />
<br />
{% endif %}
<div class="container-fluid"></div>
    <div class="row d-flex h-75 justify-content-center align-items-center mb-2">
            <div class="col-xs-12 center-block text-center">
            </div>
    </div>
    <div class="row">
        <div class="d-sm-flex align-items-center justify-content-between mb-2">
        </div>
  </div>
    <!-- Content Row start --> 
    <div class="row d-flex h-75 justify-content-center align-items-center mb-2">
    
        <div class="col-2 d-flex flex-column"></div>
    <!-- Content column start --> 

        <div class="col-8 d-flex flex-column">
    <!-- card start -->
        <div class="card shadow px-4">
          <div style="text-align:center;border:1px"><h5>Add Mutual Fund</h5></div>
            <form action='.' method='POST'>{% csrf_token %}
                <div class="form-group">

                    {{ form.productid|as_crispy_field }}

                </div>
                <div class="form-group w-50">

                    {{ form.no_shares|as_crispy_field }}

                </div>
                <div class="form-group w-50">

                    {{ form.start_date|as_crispy_field }}

                </div>
                <div class="form-group w-50">

                    {{ form.sip_date|as_crispy_field }}

                </div>
                <div class="form-group">

                    {{ form.notes|as_crispy_field }}

                </div>
                <div class="form-group">
                    <div class="text-right">
                        <button class="btn btn-info pull-right" type="submit" >Add Product</button>
                    </div>
                </div>
            </form>
        
            </div>
    <!-- card end -->
        </div>
    <!-- Content column end -->

     <div class="col-2 d-flex flex-column"></div>
    </div>
    <!-- Content Row End --> 
</div>
<script>
    $(function () {
        $("#id_sip_date").datepicker();
    });
</script>
<script>
    $(function () {
        $("#id_start_date").datepicker();
    });
</script>

{{ form.media }}
{% endblock %}

holdings/templates/holdings/addmutual3.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<h1>Create!</h1>
<br />
<form action='.' method='POST'>{% csrf_token %}
    <div class="form-row">
        <div class="col-md-6 mb-1">
            {{ form.productid|as_crispy_field  }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-2 mb-1">
            {{ form.no_shares|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-3">
            {{ form.start_date|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-3">
            {{ form.sip_date|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-4">
            {{ form.notes|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-2">
            <input type="submit" class="btn btn-primary" type="submit" value="Add Product">
        </div>
    </div>
</form>
<script>
    $( function() {
    $( "#id_sip_date").datepicker();
    } );
</script>
<script>
    $( function() {
    $( "#id_start_date").datepicker();
    } );
</script>

{{ form.media }}
{% endblock %}

holdings/templates/holdings/addmutual5.html
{% extends 'base.html' %}
{% block content %}
{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<br />

<!-- <script>
  $( function() {
      var availableTags = [
        "AxisMF",
        "AppleScript",
        "Asp",
       ];
      $( "#tags" ).autocomplete({
        source: availableTags
      });
    } );
</script>
<div class="ui-widget">
    <label for="tags">Tags: </label>
    <input id="tags">
  </div> -->
<!-- <div class="form-row">
    <div class="col-sm-6">
      <div class="form-group">
        <div class="input-group date" id="datetimepicker" data-target-input="nearest">
          <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker" />
          <div class="input-group-append" data-target="#datetimepicker" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
        <script type="text/javascript">
          $(function () {
            $(".datepicker").datepicker({
              'format': 'yy-mm-dd'

            });

          });
        </script>
      </div>
    </div>
  </div> -->
  <div class="container-fluid">
      <!-- Page Heading -->
     <!-- Content Row -->
            <div class="row">
             <div class="d-sm-flex align-items-center justify-content-between mb-2">
             </div>
           </div>
     <!-- Content Row -->
  <h1>Create!</h1>

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
  
  </div>
<!-- Content Row Start-->
<div class="row">

<form method="POST" action="{% url 'addmutual' %}" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-row">
    <div class="col-md-6 mb-3">
      <label for="Productid">Mutual Fund</label></br>
      <input class="form-control" id="ex1" type="text" list="mfunds" name="mfdlist">
      <datalist id="mfunds">
        {% for mutualfund in mutualfunds.all %}
        <option value='{{ mutualfund.title }}'>
          {% endfor %}
      </datalist>

    </div>


  </div>

  <div class="form-row">
    <div class="col-md-3 mb-3">
      <label for="no_of_shares">No of Shares</label>
      <input name="no_of_shares" type="text" class="form-control" id="no_of_shares" value="0" placeholder="50" required>
    </div>
  </div>


  <div class="form-row">
    <div class="col-sm-3">
      <div class="form-group">
        <label for="datepicker1">Start Date</label></br>
        <input name="datepicker1" id="datepicker1" width="276" />
        <script>
          $('#datepicker1').datepicker();
        </script>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col-sm-3">
      <div class="form-group">
        <label for="datepicker2">Sip Date</label></br>
        <input name="datepicker2" id="datepicker2" width="276" />
        <script>
          $('#datepicker2').datepicker();
          </script>
      </div>
    </div>
  </div>
 
  <div class="form-row">
    <div class="col-sm-2">
      <input type="submit" class="btn btn-primary btn-sm pull-right" type="submit" value="Add Product">
    </div>
  </div>
</form>
</div>
<!-- Content Row -->
</br>

{% endblock %}

holdings/templates/holdings/addmutualsip.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% if error %}
{{ error }}
<br />
<br />
{% endif %}
<div class="container-fluid"></div>
    <div class="row d-flex h-75 justify-content-center align-items-center mb-2">
            <div class="col-xs-12 center-block text-center">
            </div>
    </div>
    <div class="row">
        <div class="d-sm-flex align-items-center justify-content-between mb-2">
        </div>
  </div>
    <!-- Content Row start --> 
    <div class="row d-flex h-75 justify-content-center align-items-center mb-2">
    
        <div class="col-2 d-flex flex-column"></div>
    <!-- Content column start --> 

        <div class="col-8 d-flex flex-column">
    <!-- card start -->
        <div class="card shadow px-4">
          <div style="text-align:center;border:1px"><h5>Add Mutual Fund SIP</h5></div>
            <form action='.' method='POST' id="otherFieldDivsip">{% csrf_token %}
                <div class="form-group">

                    {{ form.productid|as_crispy_field }}

                </div>

                <div class="form-group w-50">

                    {{ form.date|as_crispy_field }}

                </div>
                <div class="form-group w-50">

                    {{ form.end_date|as_crispy_field }}

                </div>           
                  

                <div class="form-group w-50" >

                    {{ form.invest_amount|as_crispy_field }}

                </div>
                <div class="form-group">
                    <div class="text-right">
                        <button class="btn btn-info pull-right" type="submit" >Add Sip</button>
                    </div>
                </div>
            </form>

            
        
        </div>
    <!-- card end -->
        </div>
    <!-- Content column end -->

     <div class="col-2 d-flex flex-column"></div>
    </div>
    <!-- Content Row End --> 
</div>
<script>
    $(function () {
        $("#id_date").datepicker();
    });
</script>
<script>
    $(function () {
        $("#id_end_date").datepicker();
    });
</script>



{{ form.media }}
{% endblock %}

holdings/templates/holdings/editmutual.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<!-- Main Content -->
<div id="content">

<!-- Begin Page Content -->
    <div class="container-fluid">
 <!-- Page Heading -->
<!-- Content Row -->
       <div class="row">
            <div class="d-sm-flex align-items-center justify-content-between mb-2">
            </div>
      </div>
<!-- Content Row -->

        <div class="row d-flex h-75 justify-content-center align-items-center mb-2">
    
        <div class="col-2 d-flex flex-column"></div>
<!-- Content column start -->

        <div class="col-8 d-flex flex-column">
<!-- card start -->
         <div class="card shadow mx-4 my-4 p-4 ">
        
                <div style="text-align:center;border:1px"><h5>{% if not form.instance.pk %}Add a new Genre{% else %}Edit {{ form.title }}{% endif %}</h5></div>
<!-- form start -->
          <form action="" method="post">{% csrf_token %}
            <div class="form-group w-50">

            {{ form.no_shares|as_crispy_field }}

             </div>
            <div class="form-group w-50">

            {{ form.start_date|as_crispy_field }}

            </div>
            <div class="form-group w-50">

            {{ form.sip_date|as_crispy_field }}

            </div>
            <div class="form-group">

            {{ form.notes|as_crispy_field }}

            </div>
            <div class="form-group">
                <div class="text-right">   
                    <button type="submit" class="btn btn-info btn-sm pull-right">Update</button>
                </div>
            </div>
          </form>
<!-- form end -->
    </div>
<!-- card end -->
    </div>
<!-- Content column End -->
<div class="col-2 d-flex flex-column"></div>
        </div>

<!-- Content Row  End-->


    </div>
<!-- End Page Content -->

</div>
<!-- Main Content End -->


    <script>
        $(function () {
            $("#id_sip_date").datepicker();
        });
    </script>
    <script>
        $(function () {
            $("#id_start_date").datepicker();
        });
    </script>
    
   

{{ form.media }}


{% endblock %}